# Generated by Django 4.2.4 on 2023-08-08 23:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clima', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 8, 8, 23, 51, 46, 200846, tzinfo=datetime.timezone.utc))),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gravity', models.IntegerField()),
                ('population', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth', models.CharField(max_length=50)),
                ('eye', models.CharField(max_length=50)),
                ('gander', models.CharField(max_length=50, null=True)),
                ('hair', models.CharField(max_length=50)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mass', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 8, 8, 23, 51, 46, 200846, tzinfo=datetime.timezone.utc))),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet', to='main.planet')),
            ],
        ),
    ]
