# Generated by Django 4.2.4 on 2023-08-08 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 23, 54, 40, 588234, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='planet',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 23, 54, 40, 588234, tzinfo=datetime.timezone.utc)),
        ),
    ]
